---
- name: Include repo vars
  ansible.builtin.include_vars: repo.yml
  no_log: true

- name: Include default vars
  ansible.builtin.include_vars: default.yml
  no_log: true

- name: Include linux vars
  ansible.builtin.include_vars: linux.yml
  when: ansible_facts.system == 'Linux'

- name: Setup runner
  ansible.builtin.include_tasks:
    file: runner_linux.yml

- name: Setup runner systemd service
  ansible.builtin.include_tasks:
    file: service.yml
  when: ansible_facts.system == 'Linux'
