- name: Disable and Stop service
  ansible.builtin.systemd_service:
    name: github-runner.service
    state: "stopped"
    enabled: false
  become: true

- name: Get runner remove token
  ansible.builtin.uri:
    url: https://api.github.com/repos/{{ repo }}/actions/runners/remove-token
    method: POST
    status_code: 201
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ auth_token }}"
  no_log: true
  register: private_runner_remove_token
  when: organization == 'None'

- name: Set token as fact
  ansible.builtin.set_fact:
    runner_remove_token: "{{ private_runner_remove_token.json.token }}"
  no_log: true
  when: organization == 'None'

- name: Get organization runner remove token
  ansible.builtin.uri:
    url: https://api.github.com/orgs/{{ organization }}/actions/runners/remove-token
    method: POST
    status_code: 201
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ auth_token }}"
  no_log: true
  register: org_runner_remove_token
  when: organization != 'None'

- name: Set org. token as fact
  ansible.builtin.set_fact:
    runner_remove_token: "{{ org_runner_remove_token.json.token }}"
  no_log: true
  when: organization != 'None'

- name: Remove runner from repo
  ansible.builtin.command:
    chdir: "{{ service['working_dir'] }}/"
    cmd: |-
      su -c '/bin/bash config.sh remove \
      --token {{ runner_remove_token }}' "{{ service['user'] }}"
  become: true
  no_log: true
  register: return_configure_runner
  changed_when: return_configure_runner.rc != 0

- name: Remove token from fact
  ansible.builtin.set_fact:
    runner_remove_token: ""
  no_log: true

- name: Remove service file
  ansible.builtin.file:
    path: /etc/systemd/system/github-runner.service
    state: absent
  notify:
    - "Reload systemctl"
  become: true

- name: Remove working directory
  ansible.builtin.file:
    path: "{{ service['working_dir'] }}"
    state: absent
  become: true

- name: Remove runner user
  ansible.builtin.user:
    name: "{{ service['user'] }}"
    state: absent
  become: true

- name: Remove reboot cron for runner
  ansible.builtin.cron:
    name: "Ensure fully startet runner"
    state: absent
