remove_runner: false
runner_arch_git: |-
  {%- if ('arm' in ansible_facts.architecture and
    '64' in ansible_facts.architecture) or
    ('aarch' in ansible_facts.architecture and
    '64' in ansible_facts.architecture) -%}
  arm64
  {%- elif 'arm' in ansible_facts.architecture -%}
  arm
  {%- else -%}
  x64
  {%- endif -%}
